version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: todo_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_app
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuser
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  server:
    build: ./server
    container_name: todo_server
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      DB_HOST: db
      DB_USER: appuser
      DB_PASSWORD: appuser
      DB_NAME: todo_app
      RABBITMQ_URL: amqp://rabbitmq
      CLIENT_URL: http://localhost:3000
      NODE_ENV: development
      JWT_SECRET: todo_app_secret_key_2024
    ports:
      - "5000:5000"
    depends_on:
      - db
      - rabbitmq
    networks:
      - app-network

  client:
    build: ./client
    container_name: todo_client
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
